################################################################################
# Backstage ApplicationSet
# Uses Git File Generator to read config/platform-params.yaml
# Generates Application dynamically with parameterized values
################################################################################
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  
  generators:
    # Git File Generator - reads config/platform-params.yaml
    - git:
        repoURL: 'https://github.com/darede-labs/idp-platform'
        revision: 'main'
        files:
          - path: "config/platform-params.yaml"
  
  template:
    metadata:
      name: 'backstage'
      namespace: argocd
      annotations:
        # Store git params for easy reference
        repo_url: '{{.repository.url}}'
        repo_branch: '{{.repository.branch}}'
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-notifications
    
    spec:
      project: default
      
      sources:
        # Helm chart from official repo
        - repoURL: '{{.charts.backstage.repo}}'
          chart: backstage
          targetRevision: '{{.charts.backstage.version}}'
          helm:
            releaseName: backstage
            valueFiles:
              # CRITICAL: Dynamic valueFiles path
              - $values/platform-apps/backstage/values.yaml
            # Override values with parameters from config
            parameters:
              - name: global.domain
                value: '{{.infrastructure.backstageDomain}}'
              - name: global.albGroupName
                value: '{{.infrastructure.albGroupName}}'
              # Image configuration (from platform-params.yaml)
              - name: backstage.image.registry
                value: '{{.images.backstage.registry}}'
              - name: backstage.image.repository
                value: '{{.images.backstage.repository}}'
              - name: backstage.image.tag
                value: '{{.images.backstage.tag}}'
              # Ingress host must be set explicitly
              - name: ingress.host
                value: '{{.infrastructure.backstageDomain}}'
              # Ingress ALB group name (dynamic)
              - name: ingress.annotations.alb\.ingress\.kubernetes\.io/group\.name
                value: '{{.infrastructure.albGroupName}}'
              # External DNS annotation for Route53 record
              - name: ingress.annotations.external-dns\.alpha\.kubernetes\.io/hostname
                value: '{{.infrastructure.backstageDomain}}'
        
        # Values from our Git repo
        - repoURL: '{{.repository.url}}'
          targetRevision: '{{.repository.branch}}'
          ref: values
      
      destination:
        server: https://kubernetes.default.svc
        namespace: backstage
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      
      # Health assessment
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        # Ignore PostgreSQL secret data changes (Helm generates random passwords)
        - kind: Secret
          name: backstage-postgresql
          jsonPointers:
            - /data/postgres-password
